# Generated by Django 5.1.7 on 2025-04-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_analyst_current_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='analyst',
            name='specialization',
        ),
    ]
