# Generated by Django 5.1.7 on 2025-03-29 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='analyst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.analyst'),
        ),
        migrations.AddField(
            model_name='planning',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shift'),
        ),
        migrations.AlterUniqueTogether(
            name='planning',
            unique_together={('shift', 'analyst', 'plan_date')},
        ),
    ]
