# Generated by Django 5.1.7 on 2025-03-30 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='analyst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='users.analyst'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='plan_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='shifts.shift'),
        ),
    ]
