# Generated by Django 5.1.7 on 2025-04-05 13:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0002_remove_ticket_assigned_analyst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('playbook_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('incident_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ip', 'IP Address'), ('email', 'Email Address'), ('domain', 'Domain'), ('url', 'URL'), ('hash', 'File Hash'), ('subject', 'Email Subject'), ('other', 'Other')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence_score', models.IntegerField(default=50)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'value'], name='threat_inte_type_1fb1f7_idx'), models.Index(fields=['value'], name='threat_inte_value_ebc6b1_idx')],
                'unique_together': {('type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='PlaybookExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('pause_time', models.DateTimeField(blank=True, null=True)),
                ('total_paused_time', models.DurationField(default=datetime.timedelta(0))),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbook_executions', to='incidents.analysis')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbook_executions', to='incidents.incident')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='threat_intelligence.playbook')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbook_executions', to='incidents.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='PlaybookStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('is_automated', models.BooleanField(default=False)),
                ('automation_script', models.TextField(blank=True, null=True)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='threat_intelligence.playbook')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookStepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True)),
                ('playbook_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='threat_intelligence.playbookexecution')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='threat_intelligence.playbookstep')),
            ],
            options={
                'ordering': ['step__step_number'],
            },
        ),
    ]
