# Generated by Django 5.1.7 on 2025-03-30 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('users', '0002_alter_analyst_current_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('incident_type', models.CharField(max_length=100)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('sla_duration', models.DurationField(blank=True, null=True)),
                ('resolution_confirmed_timestamp', models.DateTimeField(blank=True, help_text='When client confirms resolution', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed')], default='new', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('assignment_timestamp', models.DateTimeField(blank=True, null=True)),
                ('start_timestamp', models.DateTimeField(blank=True, null=True)),
                ('completion_timestamp', models.DateTimeField(blank=True, null=True)),
                ('sla_remaining', models.DurationField(blank=True, null=True)),
                ('deadline_timestamp', models.DateTimeField(blank=True, null=True)),
                ('client_notified_timestamp', models.DateTimeField(blank=True, null=True)),
                ('client_response_timestamp', models.DateTimeField(blank=True, null=True)),
                ('assigned_analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='users.analyst')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to='incidents.incident')),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtd', models.DurationField(blank=True, help_text='Mean Time to Detect', null=True)),
                ('mta', models.DurationField(blank=True, help_text='Mean Time to Analyze', null=True)),
                ('mtr', models.DurationField(blank=True, help_text='Mean Time to Respond', null=True)),
                ('sla_met', models.BooleanField(default=False)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='incidents.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='users.analyst')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='incidents.incident')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='incidents.ticket')),
            ],
        ),
    ]
