# Generated by Django 5.1.7 on 2025-04-05 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('users', '0002_alter_analyst_current_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_analyst',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_analysts',
            field=models.ManyToManyField(blank=True, related_name='assigned_tickets', to='users.analyst'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='resolution_confirmed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='incident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='incidents.incident'),
        ),
        migrations.CreateModel(
            name='IncidentIOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incident')),
            ],
        ),
    ]
