# Generated by Django 5.1.7 on 2025-04-05 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_remove_ticket_assigned_analyst_and_more'),
        ('threat_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentioc',
            name='ioc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threat_intelligence.ioc'),
        ),
        migrations.AddField(
            model_name='incident',
            name='iocs',
            field=models.ManyToManyField(related_name='incidents', through='incidents.IncidentIOC', to='threat_intelligence.ioc'),
        ),
        migrations.AlterUniqueTogether(
            name='incidentioc',
            unique_together={('incident', 'ioc')},
        ),
    ]
