# Generated by Django 5.1.7 on 2025-04-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incidentioc_ioc_incident_iocs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('assigned', 'ASSIGNED'), ('in_progress', 'IN_PROGRESS'), ('paused', 'PAUSED'), ('completed', 'COMPLETED')], default='new', max_length=20),
        ),
    ]
